.circleci/config.yml

Add CircleCI for tests.

---

signac_dashboard/dashboard.py
signac_dashboard/views.py

Fix pagination error, simplify code.

---

examples/custom-modules/.gitignore
examples/custom-modules/README.md
examples/custom-modules/dashboard.py
examples/custom-modules/init.py
examples/custom-modules/modules/__init__.py
examples/custom-modules/modules/awesome_module.py
examples/custom-modules/templates/cards/awesome_module.html

Add custom module example.

---

signac_dashboard/dashboard.py
signac_dashboard/templates/jobs_grid.html
signac_dashboard/templates/layout.html

@csadorf caught a bug where modules weren't being enabled/disabled properly. This PR fixes that behavior.

Fix module enabling/disabling.

---

signac_dashboard/static/scss/app.scss

Long words in card titles should be broken.
Resolves #60.
If necessary:

Break words in card titles.

---

signac_dashboard/dashboard.py
signac_dashboard/templates/layout.html
signac_dashboard/views.py

Increase search box size to 100.

Increase search-box size.

---

.bumpversion.cfg
.circleci/config.yml
.circleci/deploy.bash
MANIFEST.in
changelog.txt
contributors.txt
doc/conf.py
setup.py
signac_dashboard/dashboard.py
signac_dashboard/version.py

Fixing issues with submodules in the last release.

Release 0.2.7

---

.circleci/config.yml
CONTRIBUTING.md
README.md
doc/installation.rst
setup.py

This PR drops support for Python 3.5 and brings some repository configuration up-to-date with signac and signac-flow.
If necessary:

Drop Support for Python 3.5

---

examples/flow-status/project.py
examples/kitchen-sink/dashboard.py
signac_dashboard/dashboard.py
signac_dashboard/templates/jobs_grid.html

A handful of minor updates:
- Add license header.
- Use a FlowProject in the kitchen sink example to enable flow status.
- Allow "per_page" argument in query (no user API yet).
- Add job id to section.
If necessary:

Minor updates.

---

.circleci/config.yml
.circleci/deploy.bash
changelog.txt
requirements-test.txt
requirements.txt
setup.cfg
setup.py

Switch to pytest, update CI scripts to prepare for 0.2.8 release.
If necessary:

Use pytest, update CI scripts.

---

contributors.txt
doc/conf.py
setup.cfg
setup.py
signac_dashboard/version.py

Release 0.2.8.
Mostly modernization of packaging and CI, only a few minor changes in feature scope.

Release 0.2.8

---

README.md
doc/support.rst

Point users to Slack for support. We don't actively monitor Gitter as much.
If necessary:

Point users to Slack for support.

---

.circleci/config.yml
README.md
contributors.txt
doc/conf.py
doc/installation.rst
setup.cfg
setup.py
signac_dashboard/version.py

This release patches #111 and includes a number of smaller maintenance changes to CI and docs since the last release in May 2021.

Release 0.2.9

---

changelog.txt
contributors.txt
signac_dashboard/templates/layout.html

https://user-images.githubusercontent.com/21282461/154098625-52f6dcbb-4c13-4946-8b5a-4f0e1d540ad0.mov
Resolves #93 
I'm declaring the squished sidebar as out of scope for this PR.
If necessary:

Enable selecting modules on narrow displays

---

changelog.txt
setup.py

See https://github.com/glotzerlab/signac/pull/781

Remove upper bound on python_requires.

---

.github/workflows/ci-oldest-reqs.txt
.pre-commit-config.yaml
examples/custom-modules/init.py
examples/document-editor/init.py
examples/flow-status/init.py
examples/kitchen-sink/dashboard.py
examples/minimal/dashboard.py
examples/plots/init.py
examples/wsgi/init.py
requirements.txt
setup.py
signac_dashboard/dashboard.py
signac_dashboard/modules/file_list.py
signac_dashboard/views.py
tests/test_dashboard.py

Merge after #152 is merged.
Resolves #132

Compatibility with signac 1.8

---

.pre-commit-config.yaml
signac_dashboard/modules/document_editor.py
signac_dashboard/modules/file_list.py
signac_dashboard/modules/flow_status.py
signac_dashboard/modules/image_viewer.py
signac_dashboard/modules/notes.py
signac_dashboard/modules/schema.py
signac_dashboard/modules/statepoint_list.py
signac_dashboard/modules/text_display.py
signac_dashboard/modules/video_viewer.py

Updates the pre-commit hooks for black and isort. The isort bump fixes a bug where isort cannot install due to changes to their build system poetry.
Fixes CI pre-commit tests.

Update pre-commit hooks (isort, black)

---

signac_dashboard/static/scss/app.scss
signac_dashboard/templates/jobs_grid.html
signac_dashboard/templates/layout.html
signac_dashboard/templates/project_info.html

This PR is a visual update. A couple pages had inconsistent margins and extraneous shadows. I also fixed the spacing around the checkboxes for modules along the left side.
Makes things prettier.

Minor visual updates.

---

changelog.txt
doc/security.rst
signac_dashboard/dashboard.py
signac_dashboard/templates/layout.html
signac_dashboard/templates/login.html
tests/test_dashboard.py

Adds login page to accept a token. Before, you had to paste the token in a GET request like`localhost:8895/login?token=M9CodB...`
Now paste the token in the box and it will redirect you to the page you were on before!
The new login page removes the elements that are not accessible like the search bar, views, and module list.
Resolves #160

Enable login page with redirect back to existing page

---

pyproject.toml
requirements.txt
signac_dashboard/dashboard.py
signac_dashboard/modules/text_display.py

1. Replaces `werkzeug.urls.url_encode` with `urllib.parse.urlencode` [as recommended](https://github.com/pallets/werkzeug/pull/2768/files#diff-342c3ac7878fc8165fb66b641c3a05ae0b4e5da5c9273fd00db272d61422bb89L1226).
2. Bumps flask_assets minimum version. Unfortunately, `flask_assets `[hasn't been released on conda-forge yet](https://github.com/conda-forge/flask-assets-feedstock/pull/5), but 2.1.0 works when i get it from pypi.
v2.0.0 still uses code removed from flask.
```
from flask_assets import Bundle, Environment
../../.local/lib/python3.9/site-packages/Flask_Assets-2.0-py3.9.egg/flask_assets.py:8: in <module>
from flask import _request_ctx_stack, current_app
E   ImportError: cannot import name '_request_ctx_stack' from 'flask' …
```

Support werkzeug and flask updates

---

changelog.txt
doc/support.rst

Replace the `signac-support` email address and slack link with a link to the signac discussion board.

Link to the discussion board.

---

changelog.txt
pyproject.toml

See https://github.com/glotzerlab/signac/pull/1020 for details.

Fix pyproject.toml tools -> tool.
