glotzerlab/signac-dashboard

- signac_dashboard/dashboard.py
Fetching files in job workspace subdirectories caused failures because the slashes weren't being captured in the route. This snippet describes the solution: http://flask.pocoo.org/snippets/76/
> Recognize file paths with slashes in get_file route.

- signac_dashboard/modules/image_viewer.py
- signac_dashboard/modules/video_viewer.py
This fixes an issue where Image Viewer and Video Viewer modules were using `os.path.basename` instead of returning the relative path. Previously it only worked for images/videos in the job workspace root. This fixes the behavior for matches images/videos in subdirectories.
> Fix glob paths to be relative instead of basenames

- signac_dashboard/static/scss/app.scss
@csadorf noticed that some very long statepoint parameters weren't being wrapped, and were hidden behind other cards' content. This PR resolves that behavior by adding the CSS `word-wrap: break-work;`.
Example with word-wrap:
> Wrap words in the card content.

- examples/wsgi/.gitignore
- examples/wsgi/README.md
- examples/wsgi/dashboard.py
- examples/wsgi/gunicorn_serve.sh
- examples/wsgi/init.py
- signac_dashboard/dashboard.py
WSGI is how Flask applications are meant to be run in production. When using `signac-dashboard` with the built-in Flask `app.run()` command, this notice appears:
```
* Environment: production
WARNING: Do not use the development server in a production environment.
Use a production WSGI server instead.
```
This PR exposes the Flask application's support for WSGI directly, so that servers like [gunicorn](https://gunicorn.org/), [bjoern](https://github.com/jonashaag/bjoern), or [CherryPy](https://cherrypy.org/) can be used to host the dashboard. This is supposed to be much faster and more reliable - in particular, some servers like gunicorn support multithreading and multiple workers which should scale well for handling I/O-intensive or CPU-intensive module workloads.
> Add WSGI support.

- signac_dashboard/modules/text_display.py
Slightly update the error message, I found the previous message not very helpful.
I needed to check the source code to understand that I actually need to install a package called 'markdown'.
> Clarify missing markdown library error message.

- signac_dashboard/dashboard.py
Super minor fix, merging when tests pass. Browsers automatically request `/favicon.ico` from webpages they visit. This adds a static route that points to the included favicon, to prevent 404 errors from appearing in the log.
```
127.0.0.1 - - [14/Sep/2020 22:10:16] "GET /favicon.ico HTTP/1.1" 200 -
404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
```
If necessary:
> Add route for /favicon.ico to remove 404 errors from browsers' automatic requests.

- doc/conf.py
- doc/index.rst
- doc/installation.rst
- doc/requirements.txt
- signac_dashboard/modules/flow_status.py
- signac_dashboard/modules/text_display.py
Added sphinx-codeautolink extension. https://sphinx-codeautolink.readthedocs.io/en/latest/
Minor updates to documentation.
Related: https://github.com/glotzerlab/signac-docs/issues/103
If necessary:
> Add sphinx-codeautolink extension to docs.

- changelog.txt
- signac_dashboard/modules/image_viewer.py
- signac_dashboard/modules/video_viewer.py
- signac_dashboard/views.py
Uses Flask's `send_from_directory` for safety. Users are recommended to upgrade.
Closes a potential security hole.
If necessary:
> Use send_from_directory for safety.

- .circleci/config.yml
- .github/PULL_REQUEST_TEMPLATE.md
- .pre-commit-config.yaml
- README.md
- changelog.txt
- doc/installation.rst
- pyproject.toml
- setup.py
- signac_dashboard/dashboard.py
NEP 29 has dropped support for Python < 3.8. This PR updates signac-dashboard to require Python 3.8+.
See also related changes in https://github.com/glotzerlab/signac/pull/715
If necessary:
> Require Python 3.8+, update CI.

- changelog.txt
- signac_dashboard/dashboard.py
This PR rewrites `Dashboard.add_url` to accept only one rule, and allows overriding the endpoint name if the same view function needs to be reused.
While reading over #128, I noticed a flaw in the `add_url` function. It accepts multiple rules, but if multiple rules are supplied, the endpoints are the same for each rule which results in a error being raised:
```
AssertionError: View function mapping is overwriting an existing endpoint function: get_file
```
> Permit one rule per call to add_url.

- changelog.txt
- signac_dashboard/templates/cards/file_list.html
- signac_dashboard/views.py
See #127. After a lot of testing, I have found that the only way to get the desired behavior for the default download name is to add `as_attachement` and `download_name` to where we call `flask.send_from_directory()` in `views.get_file()`. This initial change is obviously a bad solution: I'm hard-coding the filename. Some observed behavior:
- If I set `as_attachment=True` and do not send anything in `download_name`, I still do not get the correct default download file name in my Save As dialog box. The only thing this seems to change is the `Content-Disposition` response header, which changes from `inline; filename=filename.txt` when `as_attachment=False` to `attachment; filename=energy-plot-timesteps.txt` when `as_attachment=True`
- If I set `as_attachment=True` and set an undefined …
> Fix prefix_jobid issue

- changelog.txt
- signac_dashboard/dashboard.py
Reverts #129 and pulls a change from #110 that fixes support for multiple URL rules with the same view. Thanks to @cbkerr for catching my quick and messy mistake, as well as recognizing that the better solution was already given to us in the Flask docs.
This will be covered by tests when #110 is merged.
> Fix support for multiple rules

- changelog.txt
- signac_dashboard/dashboard.py
This fixes a bug from #110 where disabled modules weren't showing up in the module list.
The "disabled" state means that a module is unchecked in the grid view at launch. The module should still have a checkbox that allows users to enable it for their browser session.
Tested manually on two different dashboard projects.
> Fix bug where disabled modules don't appear in the module list.

- changelog.txt
- examples/kitchen-sink/dashboard.py
- signac_dashboard/dashboard.py
- signac_dashboard/templates/jobs_grid.html
- signac_dashboard/templates/project_info.html
This adds a config option for the number of cards per row. The default value is 3.
I have often wanted to set this to 4 cards per row instead, to make better use of screen space on large monitors.
Tested manually with a few example projects. It also works in compact mode (when only one module is enabled).
> Add option for CARDS_PER_ROW.

- .github/workflows/ci-oldest-reqs.txt
- changelog.txt
- doc/security.rst
- requirements.txt
- setup.py
- signac_dashboard/dashboard.py
- signac_dashboard/module.py
- signac_dashboard/modules/document_editor.py
- signac_dashboard/modules/notes.py
- signac_dashboard/util.py
- tests/test_dashboard.py
Following the model of Jupyter, generate a token when launched. Users must login with that token before they can view sensitive data. All routes are protected, except for static content.
This feature requires an additional dependency: `flask-login`: https://flask-login.readthedocs.io/ which appears to be the best maintained package for the job.
On multi-user systems, anyone with access to the system can connect to servers running on open ports. This opens Dashboard user's projects to be read (and written to in the case of some modules) by anyone with access to the host system. 
This pull requests prevents that access. Like Jupyter, it generates a login token when invoked on the command line. Following the security guidelines in the documentation, users will receive this token over a …
> Require login to view job and project data

- changelog.txt
- signac_dashboard/modules/image_viewer.py
Add `"*.svg"` to the default `img_globs` list for `ImageViewer`.
`svg` is a common image file format supported by all modern browsers. It can be natively generated by tools such as `matplotlib`. As a vector format, `svg` files are more readable than raster formats when the images contain text and line art. In most cases, `svg` files are also smaller than raster files.
> Add .svg to the default image viewer search.

- changelog.txt
- signac_dashboard/dashboard.py
- tests/test_dashboard.py
Correctly handle passing config arguments to the [run function of Flask](https://flask.palletsprojects.com/en/2.2.x/debugging/).
Running with
```
python dashboard.py run --debug
```
did not actually enable debug mode as indicated by the status printout
```
* Serving Flask app 'signac-dashboard'
* Debug mode: off
```
I also added keyword arguments to make it easier to follow.
> Fix to allow running in debug mode

- changelog.txt
- signac_dashboard/dashboard.py
Set PER_PAGE to 24.
With the default cards per row of 3, this makes the default view show complete rows to the end of the page. Prior to this change, the last row is left incomplete because 25 is not an integer multiple of 3.
> Show complete rows on pages by default.

- pyproject.toml
Set flask-login back to 0.6.0.
See https://github.com/glotzerlab/signac-dashboard/pull/206#issuecomment-1806649569.
> Restore flask-login dependency pinning.

- changelog.txt
- signac_dashboard/dashboard.py
The warning from signac.filterparse._cast is burried in the shell and automatically searching for capitalized boolean string is likely not the expected result.
Make the feedback when searching for booleans in incorrect JSON more like `signac find`:
```
$ signac find a True
Did you mean true?
Interpreted filter arguments as '{"a": "True"}'.
```
You would have to look at the shell to see these messages about casting of True-->true.
They come from `signac.filterparse._cast`
```shell
127.0.0.1 - - [14/Feb/2024 09:25:36] "POST /login HTTP/1.1" 302 -
Did you mean true?
Did you mean false?
Interpreted filter arguments as '{"a": "True"}'
```
Related to https://github.com/glotzerlab/signac-docs/pull/199
> Add a warning when capitalized booleans (improper JSON) appear in query
